import { fontJaro, fontJetbrainsMono } from "@/assets/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased bg-gray-100",
          fontJaro.variable,
          fontJetbrainsMono.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
